import React from 'react'
import PropTypes from 'prop-types'

class StashCreatedSuccessfully extends React.Component {
  render () {
      return(<div>
                 <div>
                      <i></i>
                      <div>
                          <div>
                             <p>Stash</p>
                             <p>Status: Completed</p>
                          </div>
                          <div>
                             <p></p>
                          </div>
                      </div>
                 </div>
             </div>)
  }
}

//export default StashCreatedSuccessfully;
